#!/usr/bin/env bash
#This is a bash script that loops from 1 to 10 and displays bad luck for the 4th loop,# good luck for the 8th loop, and Best School for the others
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]; then
	   echo "bad luck"
	elif [ $i -eq 8 ]; then
	     echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
