#!/usr/bin/env bash
# this script displays numbers from 1 to 20. when it displays 4, it then displays bad # luck from China for the displays 4 and then bad luck from China for the 4th loop ite# ration, displays 9 and then bad luck from Japan for the 9th loop iteration, displays 17 and then bad luck from Italy for the 17th loop iteration.
i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
	     4) echo "bad luck from China"
	     	;;
	9) echo "bad luck from Japan"
	   ;;
	17) echo "bad luck from Italy"
	    ;;
	esac
	i=$((i+1))
done

		